name: Keep Alive

on:
  schedule:
    # Executa a cada 5 minutos
    - cron: '*/5 * * * *'
  workflow_dispatch: # Permite execução manual

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping Health Endpoint
        run: |
          echo "Pinging health endpoint..."
          response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.RENDER_APP_URL }}/health)
          
          if [ $response -eq 200 ]; then
            echo "✅ Health check successful (HTTP $response)"
          else
            echo "⚠️ Health check returned HTTP $response"
            exit 1
          fi
      
      - name: Log Status
        run: |
          echo "Keep-alive ping completed at $(date)"
